---
abstract: 'Helper functions for the Kamstrup KEM file splitter application'
author:
  - 'Lieven Hollevoet <hollie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.029, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-KamstrupKemSplit
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  App::KamstrupKemSplit:
    file: lib/App/KamstrupKemSplit.pm
    version: '0.005'
requires:
  Archive::Zip: '0'
  Crypt::Rijndael: '0'
  Exporter: '0'
  Getopt::Long: '0'
  Log::Log4perl: '0'
  MIME::Base64: '0'
  Modern::Perl: '0'
  Pod::Usage: '0'
  Text::CSV: '0'
  XML::Simple: '0'
resources:
  bugtracker: https://github.com/hollie/app-kamstrupkemsplit-perl/issues
  repository: git://github.com/hollie/app-kamstrupkemsplit-perl.git
version: '0.005'
x_Dist_Zilla:
  perl:
    version: '5.034000'
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: 0
      name: Git::GatherDir
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.001'
          version_by_branch: 0
          version_regexp: (?^:^v(.+)$)
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.39.0
          repo_root: .
      name: Git::NextVersion
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.39.0
          repo_root: .
      name: Git::Check
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%V%n%n%c
          signoff: '0'
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.39.0
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: Git::Commit
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: build/%b
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: 0
          release_branch: releases
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.39.0
          repo_root: .
      name: Git::CommitBuild
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: releases
          changelog: Changes
          signed: 0
          tag: v0.005
          tag_format: v%v
          tag_message: v%V
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.39.0
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: Git::Tag
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
            - 'origin releases'
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.39.0
          repo_root: .
      name: Git::Push
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Starter/MetaYAML'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Starter/MetaJSON'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Starter/License'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: '@Starter/ReadmeAnyFromPod'
      version: '0.163250'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Starter/PodSyntaxTests'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Starter/Test::ReportPrereqs'
      version: '0.028'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: 0
          filename: xt/author/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: 0
          phase: develop
          script_finder:
            - ':PerlExecFiles'
          skips: []
          switch: []
      name: '@Starter/Test::Compile'
      version: '2.058'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Starter/MakeMaker'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Starter/Manifest'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Starter/PruneCruft'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Starter/ManifestSkip'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Starter/RunExtraTests'
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Starter/TestRelease'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Starter/ConfirmRelease'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Starter/UploadToCPAN'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Starter/MetaConfig'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Starter/MetaNoIndex'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Starter/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '6.029'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002004'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000037'
          version: '0.006'
      name: '@Starter/MetaProvides::Package'
      version: '2.004003'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Starter/ShareDir'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Starter/ExecDir'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: MarkdownInRoot
      version: '0.163250'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: OurPkgVersion
      version: '0.21'
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: GitHub::Meta
      version: '0.48'
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: PruneFiles
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Starter/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '6.029'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.029'
x_generated_by_perl: v5.34.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
